---
title: "Youth Mental Health & Social Media"
author: "Dean Marchiori"
format: html
execute:
  echo: true
  warning: false
  message: false
---
```{r}
library(tidyverse)
library(here)
library(themes360info)  #360Info internal package: `remotes::install_github("360-info/themes360info")` 
library(sf)
library(mapdeck)
library(glue)
```


## Plot  

Showing symmetric age pyramid, split by gender for Mental Health prevalance. 

This version shows **count of persons**  

```{r}
#| fig-height: 8
#| fig-width: 8

mh <- read_csv(here("data/final/mental_health_census.csv"))

# This is a helper function for the symmetric bar plot
pretty_symmetric <- function(range, n = 5) {
    range_1 <- c(-range[1], range[2])
    range_2 <- c(range[1], -range[2])

    pretty_vec_1 <- pretty(range_1)
    pretty_vec_2 <- pretty(range_2)

    pretty(
        c(pretty_vec_1, pretty_vec_2),
        n = n
    )
}

abs_plot_1 <- ggplot(mh, aes(condition_directional, age, fill = gender)) +
    geom_col(aes(alpha = alpha_channel)) +
    scale_x_continuous(
        breaks = pretty_symmetric(range(mh$condition_directional)),
        labels = scales::comma(abs(pretty_symmetric(range(mh$condition_directional))))
    ) +
    expand_limits(x = pretty_symmetric(range(mh$condition_directional))) +
    scale_fill_manual(values = c("#36a7e9", "#2d3494"))+
    scale_alpha(range = c(0.6, 1)) +
    guides(alpha = "none") +
    themes360info::theme_360() +
    labs(
        title = "Persons with a mental health condition",
        subtitle = "Has been told by a doctor or nurse that they have a **mental health condition**<br>*(including depression or anxiety)*",
        caption = "**Source**: Based on Australian Bureau of Statistics data.",
        x = "Count of Persons",
        y = "Age",
        fill = "Gender"
    ) +
    annotate_360_lightblue(
        x = 210000, y = 9.1, size = 3, 
        label = "**Young people** make up a<br> large proprtion of overall sufferers<br> of mental health conditions.<br> **Females** are much more heavily impacted."
    ) 

save_360plot(abs_plot_1, here("out/img/abs_plot_1.png"), shape = "square")

abs_plot_1
```

Showing symmetric age pyramid, split by gender for Mental Health prevalance. 

This version shows **Proportion of persons**  


```{r}
#| fig-height: 8
#| fig-width: 8

abs_plot_2 <- ggplot(mh, aes(proportion_directional, age, fill = gender)) +
    geom_col(aes(alpha = alpha_channel)) +
    scale_x_continuous(
        breaks = pretty_symmetric(range(mh$proportion_directional)),
        labels = scales::percent(abs(pretty_symmetric(range(mh$proportion_directional))))
    ) +
    expand_limits(x = pretty_symmetric(range(mh$proportion_directional))) +
    scale_fill_manual(values = c("#36a7e9", "#2d3494"))+
    scale_alpha(range = c(0.6, 1)) +
    guides(alpha = "none") +
    themes360info::theme_360() +
    labs(
        title = "Proportion of persons in each age group\nwith a mental health condition",
        subtitle = "Has been told by a doctor or nurse that they have a **mental health condition**<br>*(including depression or anxiety)*",
        caption = "**Source**: Based on Australian Bureau of Statistics data.",
        x = "Proportion of persons in each age group",
        y = "Age",
        fill = "Gender"
    ) +
    annotate_360_lightblue(
        x = -0.1, y = 9.1, size = 3, 
        label = "A high proportion of persons in **Youth** age <br>groups suffer from mental health conditions.<br> **Females** are much more heavily impacted."
    ) 

save_360plot(abs_plot_2, here("out/img/abs_plot_2.png"), shape = "square")

abs_plot_2
```


# Mental Health Map  

Read in data

```{r}
mh_moran <- sf::read_sf(here("data/final/mental_health_hotspot.geojson"))
```

visualise lags vs actuals 

```{r}
#| eval: false 

ggplot(mh_moran, aes(prop, prop_lag)) +
    geom_point() +
    geom_vline(aes(xintercept = mean(prop)), lty = 2) +
    geom_hline(aes(yintercept = mean(prop_lag)), lty = 2) +
    geom_smooth(method = "lm")
```

Produce graphic 

```{r}
#| eval: false
state_data <- mh_moran |>
    select(state, mean, alpha_channel) |>
    group_split(state)

make_plot <- function(data) {
    p <- ggplot(data, aes(fill = mean)) +
        geom_sf(aes(alpha = alpha_channel), color = "grey80", show.legend = FALSE) +
       # labs(title = unique(data$state)) +
       scale_alpha(range = c(0.6, 1)) +
        scale_fill_manual(values = c("#36a7e9", "#e1e4e6"), na.value = "#e1e4e6") +
        theme_void()
}

state_plots <- map(state_data[c(1, 3, 5, 6)], make_plot)

pw <- (state_plots[[1]] / state_plots[[4]]) | (state_plots[[3]] / state_plots[[2]])

x <- pw +
    plot_annotation(caption = "Mental Health **HOTSPOTS** for eastern states.<br>*Source: Based on ABS data.*") &
    themes360info::theme_360() +
    theme(panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
     axis.text = element_blank())

x 

themes360info::save_360plot(x, "out/hot_spot.png")
```

::: {.panel-tabset}

```{r}
poly_lay <- mh_moran |>
    sf::st_transform(4326) |>
    select(SA2_NAME_2021, mean, state, total, prop, prop_lag) |>
    filter(!is.na(mean))  |>
    mutate(tooltip = glue("Suburb: {SA2_NAME_2021}<br>Hot Spot<br>Mental Health Proportion (Ages 15-24): {round(prop, 2)}%<br>Surrounding Average: {round(prop_lag, 2)}%"))

```

# NSW 

```{r}
nsw <- poly_lay |>
    filter(
        state == "NSW/ACT"
    )

mapdeck() %>%
    add_polygon(
        data = nsw,
        fill_colour = "prop",
       # fill_opacity = "total",
        elevation = "prop",
        elevation_scale = 1000,
        palette = "heat",
        tooltip = "tooltip",
        auto_highlight = TRUE,
        legend = TRUE
    )

```

# SA

```{r}
sa <- poly_lay |>
    filter(state == "SA")

mapdeck() %>%
    add_polygon(
        data = sa,
        fill_colour = "prop",
       # fill_opacity = "total",
        elevation = "prop",
        elevation_scale = 1000,
        palette = "heat",
        tooltip = "tooltip",
        auto_highlight = TRUE,
        legend = TRUE
    )

```

:::

